name: qr_proyect
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.3 <4.0.0'

dependencies:
  firebase_core: ^2.30.1
  flutter:
    sdk: flutter
  firebase_auth: 4.19.2
  google_sign_in: 6.2.1
  sign_in_button: ^3.2.0
  geolocator: ^7.0.3
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
